## those stages are copied from https://gitlab.com/gitlab-org/gitlab-foss/-/blob/master/lib/gitlab/ci/templates/Auto-DevOps.gitlab-ci.yml
## the only thing we change is putting test before build, this way we first test, then build.
## the rest is the same and will be picked up by Auto-Devops
stages:
  - ktlint
  - test
  - build
  - deploy  # dummy stage to follow the template guidelines
  - pages
  - review
  - dast
  - staging
  - canary
  - production
  - incremental rollout 10%
  - incremental rollout 25%
  - incremental rollout 50%
  - incremental rollout 100%
  - performance
  - cleanup

# enable pipelines for merge requests and master branch
workflow:
  rules:
    - if: $CI_MERGE_REQUEST_ID               # Execute jobs in merge request context
    - if: $CI_COMMIT_BRANCH == 'master'

cache:
  key: "$CI_PROJECT_ID"
  paths:
    - .gradle/wrapper
    - .gradle/caches
#  policy: pull

before_script:
  - export GRADLE_USER_HOME=$CI_PROJECT_DIR/.gradle

variables:
  DOCKER_HOST: "tcp://docker:2375"
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  POSTGRES_ENABLED: "false"
  CODE_QUALITY_DISABLED: "true"
  SAST_DISABLED: "true"
  PERFORMANCE_DISABLED: "true"

test:
  image: openjdk:17-alpine
  stage: test
  rules:
    - if: '$CI_COMMIT_BRANCH || $CI_MERGE_REQUEST_ID'
  services:
    - docker:dind
  artifacts:
    when: always
    expire_in: 1 week
    name: '$CI_COMMIT_REF_NAME'
    reports:
      junit: build/test-results/test/**/TEST-*.xml
  dependencies: [ ]
  script:
    - ./gradlew -Dorg.gradle.daemon=false test --info

ktlint:
  image: openjdk:17-alpine
  stage: test
  only:
    - branches
    - merge_requests
  artifacts:
    when: always
    expire_in: 1 week
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - build/reports/
  dependencies: [ ]
  script:
    - ./gradlew -Dorg.gradle.daemon=false ktlintCheck --info

build:
  rules:
    - if: '$CI_COMMIT_BRANCH || $CI_MERGE_REQUEST_ID'

production:
  rules:
    - if: '$CI_COMMIT_BRANCH'

secret_detection_default_branch:
  rules:
    - when: never

include:
  - template: Auto-DevOps.gitlab-ci.yml