/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.iliassk.dev

import io.kotest.matchers.shouldBe
import kotlin.test.Test

class AppTest {
    @Test
    fun `should have a greeting`() {
        val classUnderTest = App()
        classUnderTest.greeting shouldBe "Welcome to the AnagramChecker!"
    }
}

