/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.iliassk.dev

class App {
    val greeting: String
        get() {
            return "Hello to the AnagramChecker!"
        }
}


fun main() {
    println(App().greeting)
    println("Please enter a first word: ")
    val word1 = requireNotNull(readLine())
    println("Please enter a second word: ")
    val word2 = requireNotNull(readLine())

    val checker = AnagramChecker()
    val result = checker.areAnagrams(word1, word2)
    if(result) println("The 2 words are anagrams.")
    else println("The 2 words are not anagrams.")
}
